# Generated by Django 3.0.8 on 2020-11-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mta_status_indexer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
